In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data=pd.read_excel('/Users/ningyuding/Desktop/douyin/total.xlsx')

In [3]:
data.head()

   排名      月份           品牌名称    品牌类型      预估销售额    预估销量   推广商品  关联直播  关联视频
0   1  202102  Teenie Weenie    服饰内衣  158431046  360484    950    82     2
1   2  202102            奢品匯    鞋靴箱包  124360036   25956  40134   456     0
2   3  202102             出处    二手闲置   98373788   22603   8017   182     0
3   4  202102            太平鸟    服饰内衣   84882867  294201   2687   522    38
4   5  202102             华为  3C数码家电   78532950  159364   2142  1413   146

In [4]:
data.shape

(4000, 9)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   排名      4000 non-null   int64
 1   月份      4000 non-null   int64
 2   品牌名称    4000 non-null   object
 3   品牌类型    4000 non-null   object
 4   预估销售额   4000 non-null   int64
 5   预估销量    4000 non-null   int64
 6   推广商品    4000 non-null   int64
 7   关联直播    4000 non-null   int64
 8   关联视频    4000 non-null   int64
dtypes: int64(7), object(2)
memory usage: 281.4+ KB

In [6]:
data.预估销售额.describe()

count    4.000000e+03
mean     9.456982e+06
std      1.582184e+07
min      1.422408e+06
25%      3.545904e+06
50%      5.042442e+06
75%      9.532548e+06
max      2.562988e+08
Name: 预估销售额, dtype: float64

In [7]:
data.预估销量.describe()

count    4.000000e+03
mean     1.021050e+05
std      1.992799e+05
min      1.600000e+01
25%      2.021150e+04
50%      4.966750e+04
75%      1.140735e+05
max      7.006089e+06
Name: 预估销量, dtype: float64

In [8]:
data.dtypes

排名        int64
月份        int64
品牌名称     object
品牌类型     object
预估销售额     int64
预估销量      int64
推广商品      int64
关联直播      int64
关联视频      int64
dtype: object

In [9]:
#data['月份']=pd.to_datetime(data.loc[:,'月份'],format='%m/%Y',errors='coerce')

In [10]:
datasum=data.groupby(['品牌类型','月份']).sum()[['预估销售额','预估销量']]

In [11]:
datasum

                    预估销售额      预估销量
品牌类型   月份
3C数码家电 202102   331961306    934571
       202103   782977010   1261251
       202104   611034884   1565271
       202105   419255615   1330969
个护家清   202102   174585770   2360560
...                   ...       ...
鞋靴箱包   202105   870128737   5401784
食品饮料   202102   636595734  10899451
       202103  1234891096  28234489
       202104  1413420774  30983695
       202105  1491648341  30140745

[69 rows x 2 columns]

In [12]:
datasum.to_excel("/Users/ningyuding/Desktop/douyin/analysissum.xlsx")

In [13]:
dataavg=data.groupby(['品牌类型','月份']).mean()[['预估销售额','预估销量']]

In [14]:
dataavg=dataavg.rename(columns={'预估销售额':'平均预告销售额','预估销量':'平均预告销量'})

In [15]:
dataavg

                    平均预告销售额         平均预告销量
品牌类型   月份
3C数码家电 202102  7.903841e+06   22251.690476
       202103  2.237077e+07   36035.742857
       202104  1.651446e+07   42304.621622
       202105  1.270472e+07   40332.393939
个护家清   202102  4.156804e+06   56203.809524
...                     ...            ...
鞋靴箱包   202105  1.500222e+07   93134.206897
食品饮料   202102  3.789260e+06   64877.684524
       202103  6.499427e+06  148602.573684
       202104  7.248312e+06  158890.743590
       202105  8.475275e+06  171254.232955

[69 rows x 2 columns]

In [16]:
category=pd.merge(datasum, dataavg, on=['品牌类型','月份'])

In [17]:
category

                    预估销售额      预估销量       平均预告销售额         平均预告销量
品牌类型   月份
3C数码家电 202102   331961306    934571  7.903841e+06   22251.690476
       202103   782977010   1261251  2.237077e+07   36035.742857
       202104   611034884   1565271  1.651446e+07   42304.621622
       202105   419255615   1330969  1.270472e+07   40332.393939
个护家清   202102   174585770   2360560  4.156804e+06   56203.809524
...                   ...       ...           ...            ...
鞋靴箱包   202105   870128737   5401784  1.500222e+07   93134.206897
食品饮料   202102   636595734  10899451  3.789260e+06   64877.684524
       202103  1234891096  28234489  6.499427e+06  148602.573684
       202104  1413420774  30983695  7.248312e+06  158890.743590
       202105  1491648341  30140745  8.475275e+06  171254.232955

[69 rows x 4 columns]

In [18]:
category.to_excel("/Users/ningyuding/Desktop/douyin/汇总.xlsx")

In [20]:
import matplotlib as mpl
import seaborn as sns
sns.set(color_codes=True)
mpl.rcParams["font.sans-serif"] = ["SimHei"]
mpl.rcParams["axes.unicode_minus"] = False

In [ ]:
X=category.(['品牌类型'])
X1=category.(['月份'])

In [24]:
data

,排名,月份,品牌名称,品牌类型,预估销售额,预估销量,推广商品,关联直播,关联视频
0,1,202102,Teenie Weenie,服饰内衣,158431046,360484,950,82,2
1,2,202102,奢品匯,鞋靴箱包,124360036,25956,40134,456,0
2,3,202102,出处,二手闲置,98373788,22603,8017,182,0
3,4,202102,太平鸟,服饰内衣,84882867,294201,2687,522,38
4,5,202102,华为,3C数码家电,78532950,159364,2142,1413,146
...,...,...,...,...,...,...,...,...,...
3995,996,202105,韩水仙,美妆,3565833,82913,59,3916,147
3996,997,202105,妙可蓝多,食品饮料,3564342,49694,76,1449,91
3997,998,202105,低卡博士,食品饮料,3563804,189265,92,8517,424
3998,999,202105,BONAS/宝娜斯,服饰内衣,3562882,123328,208,438,20
3999,1000,202105,独角兽暴肌厨房,食品饮料,3562492,119321,101,13794,592

In [46]:
data.sort_values(by=['预估销量'], ascending = False) 
res = data.groupby('品牌类型').head(50)
res

       排名      月份       品牌名称  品牌类型     预估销售额     预估销量  推广商品   关联直播  关联视频
3161  162  202105        南极人  服饰内衣  17585437  7006089  2888  22861  1442
3029   30  202105         雅鹿  服饰内衣  47896292  4218519  4687   3939   628
2243  244  202104        南极人  服饰内衣  10055069  3253565  1798  18314  1041
1172  173  202103        尚美度  鞋靴箱包  13037400  1698267    88     75    25
2061   62  202104       本该时鲜    生鲜  26430814  1691948   310  45209  4717
...   ...     ...        ...   ...       ...      ...   ...    ...   ...
3355  356  202105        小花苗  二手闲置   9455334     1763  4523     88     0
2284  285  202104        小花苗  二手闲置   8699475     1735  3991     72     0
926   927  202102  iluminage    其他   1549966     1034     2      0    11
1663  664  202103        铂爵游  本地生活   4030364      803     2      4     0
891   892  202102     WF原创设计  玩具乐器   1599983       16     1      0    11

[743 rows x 9 columns]

In [43]:
res.to_excel("/Users/ningyuding/Desktop/douyin/res.xlsx",)

In [33]:
data

,排名,月份,品牌名称,品牌类型,预估销售额,预估销量,推广商品,关联直播,关联视频
3161,162,202105,南极人,服饰内衣,17585437,7006089,2888,22861,1442
3029,30,202105,雅鹿,服饰内衣,47896292,4218519,4687,3939,628
2243,244,202104,南极人,服饰内衣,10055069,3253565,1798,18314,1041
1172,173,202103,尚美度,鞋靴箱包,13037400,1698267,88,75,25
2061,62,202104,本该时鲜,生鲜,26430814,1691948,310,45209,4717
...,...,...,...,...,...,...,...,...,...
659,660,202102,NAME LUXURY EXCHANGE /名奢汇,钟表配饰,2201642,140,126,43,0
2888,889,202104,预麦,二手闲置,3301320,70,673,60,0
823,824,202102,预麦,二手闲置,1724452,48,499,64,0
402,403,202102,勤玉珠宝,珠宝文玩,3599964,36,3,8,0
891,892,202102,WF原创设计,玩具乐器,1599983,16,1,0,11

In [31]:
res

,排名,月份,品牌名称,品牌类型,预估销售额,预估销量,推广商品,关联直播,关联视频
3161,162,202105,南极人,服饰内衣,17585437,7006089,2888,22861,1442
3029,30,202105,雅鹿,服饰内衣,47896292,4218519,4687,3939,628
2243,244,202104,南极人,服饰内衣,10055069,3253565,1798,18314,1041
1172,173,202103,尚美度,鞋靴箱包,13037400,1698267,88,75,25
2061,62,202104,本该时鲜,生鲜,26430814,1691948,310,45209,4717
...,...,...,...,...,...,...,...,...,...
659,660,202102,NAME LUXURY EXCHANGE /名奢汇,钟表配饰,2201642,140,126,43,0
2888,889,202104,预麦,二手闲置,3301320,70,673,60,0
823,824,202102,预麦,二手闲置,1724452,48,499,64,0
402,403,202102,勤玉珠宝,珠宝文玩,3599964,36,3,8,0
891,892,202102,WF原创设计,玩具乐器,1599983,16,1,0,11

In [28]:
data.sort_values('预估销量', ascending = False, inplace=True)

In [29]:
res = data.groupby(['品牌类型','月份','品牌名称']).head(10)

In [30]:
res

,排名,月份,品牌名称,品牌类型,预估销售额,预估销量,推广商品,关联直播,关联视频
3161,162,202105,南极人,服饰内衣,17585437,7006089,2888,22861,1442
3029,30,202105,雅鹿,服饰内衣,47896292,4218519,4687,3939,628
2243,244,202104,南极人,服饰内衣,10055069,3253565,1798,18314,1041
1172,173,202103,尚美度,鞋靴箱包,13037400,1698267,88,75,25
2061,62,202104,本该时鲜,生鲜,26430814,1691948,310,45209,4717
...,...,...,...,...,...,...,...,...,...
659,660,202102,NAME LUXURY EXCHANGE /名奢汇,钟表配饰,2201642,140,126,43,0
2888,889,202104,预麦,二手闲置,3301320,70,673,60,0
823,824,202102,预麦,二手闲置,1724452,48,499,64,0
402,403,202102,勤玉珠宝,珠宝文玩,3599964,36,3,8,0
891,892,202102,WF原创设计,玩具乐器,1599983,16,1,0,11

In [155]:
datasumbrand=data.groupby(['品牌类型','月份','品牌名称'])#.sum()[['预估销售额','预估销量']].sort_values(by=['预估销量'],ascending=False)

In [158]:
print(datasumbrand)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7fd59b100f70>

In [157]:
datasumbrand.to_excel("/Users/ningyuding/Desktop/douyin/analysisbrand.xlsx",sheet_name='sumbrand')

AttributeError: 'DataFrameGroupBy' object has no attribute 'to_excel'

In [146]:
sorteddatasumbrand=datasumbrand.sort_values(by=['预估销量'],ascending=False).groupby()

In [147]:
sorteddatasumbrand

                                          预估销售额     预估销量
品牌类型 月份     品牌名称
服饰内衣 202105 南极人                        17585437  7006089
            雅鹿                         47896292  4218519
     202104 南极人                        10055069  3253565
鞋靴箱包 202103 尚美度                        13037400  1698267
生鲜   202104 本该时鲜                       26430814  1691948
...                                         ...      ...
钟表配饰 202102 NAME LUXURY EXCHANGE /名奢汇   2201642      140
二手闲置 202104 预麦                          3301320       70
     202102 预麦                          1724452       48
珠宝文玩 202102 勤玉珠宝                        3599964       36
玩具乐器 202102 WF原创设计                      1599983       16

[4000 rows x 2 columns]

In [149]:
sorteddatasumbrand.to_excel("/Users/ningyuding/Desktop/douyin/sorteddatasumbrand.xlsx")

In [135]:
#datasumbrand=datasumbrand.sort_values(['预估销量'],ascending=False).groupby(['品牌类型','月份','品牌名称'])

In [137]:
#datasumbrand

In [131]:
#datasumbrandsort=data.groupby(['品牌类型','月份','品牌名称', group_keys=False]).sum()[['预估销售额','预估销量']].apply(lambda x: x.sort_values('预估销售额',ascending=False))

In [132]:
#datasumbrandsort

In [133]:
dataavgbrand=data.groupby(['品牌类型','品牌名称']).mean()[['预估销售额','预估销量']]

In [134]:
dataavgbrand

                               预估销售额           预估销量
品牌类型   品牌名称
3C数码家电 CHARMOON         1.805571e+06  122273.000000
       CINKICC          5.493490e+06   54225.000000
       Citin/村田         3.839484e+06    2958.000000
       DIGITALWOLF/数码狼  2.063282e+06  153840.000000
       IQOO             9.549632e+06    5576.000000
...                              ...            ...
食品饮料   高美奇(gaomeiqi)    4.049781e+06  410131.000000
       鲨鱼菲特             9.004395e+06   71337.333333
       麦芽之路             3.287223e+06   20830.500000
       黄金酒              4.741054e+06   73838.500000
       龙船爱菲尔            2.112265e+06   15237.000000

[1836 rows x 2 columns]